=== elifesciences/spa-patterns-workshop/patterns-php/resources/schemas/site-header.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "minLength": 1
    },
    "homeUrl": {
      "type": "string",
      "minLength": 1
    },
    "text": {
      "type": "string",
      "minLength": 1
    },
    "menu": {
      "$ref": "menu.schema.json"
    }
  },
  "required": [
    "title",
    "homeUrl",
    "text"
  ]
}

=== elifesciences/spa-patterns-workshop/patterns/source/_patterns/02-organisms/components/site-header.json
{
  "title": "Some company",
  "homeUrl": "#",
  "text": "Synergizing your virtual interfaces to disintermediate open-source e-commerce",
  "menu": {
    "items": [
      {
        "text": "page 1",
        "url": "#",
        "isCurrent": true
      },
      {
        "text": "page 2",
        "url": "#"
      }
    ]
  }
}
